// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "dank";    // Network SSID (name)
const char PASS[]     = "reallydank";    // Network password (use for WPA, or use as key for WEP)

void onShotSizeChange();
void onScheduleChange();
void onBrewBoilerOnChange();
void onSteamBoilerOnChange();

String _State;
CloudCounter _FlowMeter;
CloudCounter _ShotSize;
CloudTemperatureSensor _BrewBoilerTemperature;
CloudTemperatureSensor _SteamBoilerTemperature;
CloudSchedule _Schedule;
bool _BrewBoilerOn;
bool _SteamBoilerOn;
CloudTime _ShotTimer;

void initProperties(){

  ArduinoCloud.addProperty(_State, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(_FlowMeter, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(_ShotSize, READWRITE, 1 * SECONDS, onShotSizeChange);
  ArduinoCloud.addProperty(_BrewBoilerTemperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(_SteamBoilerTemperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(_Schedule, READWRITE, 1 * SECONDS, onScheduleChange);
  ArduinoCloud.addProperty(_BrewBoilerOn, READWRITE, 1 * SECONDS, onBrewBoilerOnChange);
  ArduinoCloud.addProperty(_SteamBoilerOn, READWRITE, 1 * SECONDS, onSteamBoilerOnChange);
  ArduinoCloud.addProperty(_ShotTimer, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
